### ISSUE TITLE
压缩功能有问题

### ISSUE THREAD

**Issue by lugreen** [JacksonTian/ping#1]
在启用了压缩后，下载css文件时浏览器与服务器的链接好像不会断开，浏览器呈假死状态。
在配置文件中禁用压缩后可正常访问。
操作系统:win7 64位

**Comment by stephansun** [comment]
这个应该是 asset.js 和 app.js （app.js 对应最开始版本的静态服务器，asset.js对应后来综合版本里的静态服务器）中的 `response.setHeader('Content-Length', stats.size);` 这一行导致的，大约原因是面对压缩比比较大的CSS文件（比方说从几百K压缩成几十K），这里的Content-Length是原始文件的大小，浏览器识别到这个值后会一直等待读取，而事实上压缩后的文件早传完了，所以造成“浏览器呈假死状态”，直到浏览器2分钟超时。将这一行注释即可解决这个问题。
